// flow-typed signature: 3884ef64c0813b02e65700ba642cf6b9
// flow-typed version: <<STUB>>/better-react-spinkit_v^2.0.0-4/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'better-react-spinkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'better-react-spinkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'better-react-spinkit/dist/Base/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/Base/Circle' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/Base/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/ChasingDots/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/ChasingDots/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/Circle/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/Circle/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/CubeGrid/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/CubeGrid/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/CubeGrid/randomDelays' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/DoubleBounce/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/DoubleBounce/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/FadingCircle/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/FadingCircle/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/FoldingCube/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/FoldingCube/cubeDelay' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/FoldingCube/cubeRotateZ' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/FoldingCube/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/Pulse/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/Pulse/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/RotatingPlane/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/RotatingPlane/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/ThreeBounce/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/ThreeBounce/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/util/animate' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/util/animationName' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/util/defaults' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/util/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/util/preside' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/WanderingCubes/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/WanderingCubes/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/Wave/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/Wave/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/Wordpress/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/dist/Wordpress/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/Base/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/Base/Circle' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/Base/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/ChasingDots/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/ChasingDots/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/Circle/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/Circle/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/CubeGrid/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/CubeGrid/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/CubeGrid/randomDelays' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/DoubleBounce/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/DoubleBounce/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/FadingCircle/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/FadingCircle/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/FoldingCube/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/FoldingCube/cubeDelay' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/FoldingCube/cubeRotateZ' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/FoldingCube/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/Pulse/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/Pulse/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/RotatingPlane/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/RotatingPlane/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/ThreeBounce/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/ThreeBounce/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/util/animate' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/util/animationName' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/util/defaults' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/util/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/util/preside' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/WanderingCubes/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/WanderingCubes/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/Wave/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/Wave/index' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/Wordpress/__spec__/index.spec' {
  declare module.exports: any;
}

declare module 'better-react-spinkit/src/Wordpress/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'better-react-spinkit/dist/Base/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/Base/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/dist/Base/Circle.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/Base/Circle'>;
}
declare module 'better-react-spinkit/dist/Base/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/Base/index'>;
}
declare module 'better-react-spinkit/dist/ChasingDots/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/ChasingDots/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/dist/ChasingDots/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/ChasingDots/index'>;
}
declare module 'better-react-spinkit/dist/Circle/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/Circle/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/dist/Circle/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/Circle/index'>;
}
declare module 'better-react-spinkit/dist/CubeGrid/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/CubeGrid/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/dist/CubeGrid/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/CubeGrid/index'>;
}
declare module 'better-react-spinkit/dist/CubeGrid/randomDelays.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/CubeGrid/randomDelays'>;
}
declare module 'better-react-spinkit/dist/DoubleBounce/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/DoubleBounce/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/dist/DoubleBounce/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/DoubleBounce/index'>;
}
declare module 'better-react-spinkit/dist/FadingCircle/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/FadingCircle/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/dist/FadingCircle/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/FadingCircle/index'>;
}
declare module 'better-react-spinkit/dist/FoldingCube/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/FoldingCube/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/dist/FoldingCube/cubeDelay.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/FoldingCube/cubeDelay'>;
}
declare module 'better-react-spinkit/dist/FoldingCube/cubeRotateZ.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/FoldingCube/cubeRotateZ'>;
}
declare module 'better-react-spinkit/dist/FoldingCube/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/FoldingCube/index'>;
}
declare module 'better-react-spinkit/dist/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/index'>;
}
declare module 'better-react-spinkit/dist/Pulse/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/Pulse/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/dist/Pulse/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/Pulse/index'>;
}
declare module 'better-react-spinkit/dist/RotatingPlane/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/RotatingPlane/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/dist/RotatingPlane/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/RotatingPlane/index'>;
}
declare module 'better-react-spinkit/dist/ThreeBounce/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/ThreeBounce/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/dist/ThreeBounce/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/ThreeBounce/index'>;
}
declare module 'better-react-spinkit/dist/util/animate.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/util/animate'>;
}
declare module 'better-react-spinkit/dist/util/animationName.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/util/animationName'>;
}
declare module 'better-react-spinkit/dist/util/defaults.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/util/defaults'>;
}
declare module 'better-react-spinkit/dist/util/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/util/index'>;
}
declare module 'better-react-spinkit/dist/util/preside.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/util/preside'>;
}
declare module 'better-react-spinkit/dist/WanderingCubes/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/WanderingCubes/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/dist/WanderingCubes/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/WanderingCubes/index'>;
}
declare module 'better-react-spinkit/dist/Wave/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/Wave/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/dist/Wave/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/Wave/index'>;
}
declare module 'better-react-spinkit/dist/Wordpress/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/Wordpress/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/dist/Wordpress/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/dist/Wordpress/index'>;
}
declare module 'better-react-spinkit/src/Base/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/Base/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/src/Base/Circle.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/Base/Circle'>;
}
declare module 'better-react-spinkit/src/Base/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/Base/index'>;
}
declare module 'better-react-spinkit/src/ChasingDots/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/ChasingDots/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/src/ChasingDots/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/ChasingDots/index'>;
}
declare module 'better-react-spinkit/src/Circle/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/Circle/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/src/Circle/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/Circle/index'>;
}
declare module 'better-react-spinkit/src/CubeGrid/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/CubeGrid/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/src/CubeGrid/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/CubeGrid/index'>;
}
declare module 'better-react-spinkit/src/CubeGrid/randomDelays.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/CubeGrid/randomDelays'>;
}
declare module 'better-react-spinkit/src/DoubleBounce/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/DoubleBounce/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/src/DoubleBounce/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/DoubleBounce/index'>;
}
declare module 'better-react-spinkit/src/FadingCircle/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/FadingCircle/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/src/FadingCircle/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/FadingCircle/index'>;
}
declare module 'better-react-spinkit/src/FoldingCube/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/FoldingCube/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/src/FoldingCube/cubeDelay.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/FoldingCube/cubeDelay'>;
}
declare module 'better-react-spinkit/src/FoldingCube/cubeRotateZ.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/FoldingCube/cubeRotateZ'>;
}
declare module 'better-react-spinkit/src/FoldingCube/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/FoldingCube/index'>;
}
declare module 'better-react-spinkit/src/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/index'>;
}
declare module 'better-react-spinkit/src/Pulse/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/Pulse/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/src/Pulse/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/Pulse/index'>;
}
declare module 'better-react-spinkit/src/RotatingPlane/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/RotatingPlane/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/src/RotatingPlane/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/RotatingPlane/index'>;
}
declare module 'better-react-spinkit/src/ThreeBounce/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/ThreeBounce/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/src/ThreeBounce/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/ThreeBounce/index'>;
}
declare module 'better-react-spinkit/src/util/animate.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/util/animate'>;
}
declare module 'better-react-spinkit/src/util/animationName.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/util/animationName'>;
}
declare module 'better-react-spinkit/src/util/defaults.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/util/defaults'>;
}
declare module 'better-react-spinkit/src/util/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/util/index'>;
}
declare module 'better-react-spinkit/src/util/preside.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/util/preside'>;
}
declare module 'better-react-spinkit/src/WanderingCubes/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/WanderingCubes/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/src/WanderingCubes/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/WanderingCubes/index'>;
}
declare module 'better-react-spinkit/src/Wave/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/Wave/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/src/Wave/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/Wave/index'>;
}
declare module 'better-react-spinkit/src/Wordpress/__spec__/index.spec.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/Wordpress/__spec__/index.spec'>;
}
declare module 'better-react-spinkit/src/Wordpress/index.js' {
  declare module.exports: $Exports<'better-react-spinkit/src/Wordpress/index'>;
}
