// flow-typed signature: cccf387a49a5067c55a656669599a933
// flow-typed version: <<STUB>>/font-awesome_v^4.6.3/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'font-awesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'font-awesome' {
  declare module.exports: any;
}
