// flow-typed signature: f94098bae55d5910adf09bde71f8fa43
// flow-typed version: <<STUB>>/ionicons_v^3.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ionicons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ionicons' {
  declare module.exports: any;
}
