// flow-typed signature: 02f555e98b5a544f0fe817fed0f10cb6
// flow-typed version: <<STUB>>/js-base64_v^2.1.9/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-base64'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-base64' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-base64/base64' {
  declare module.exports: any;
}

declare module 'js-base64/base64.min' {
  declare module.exports: any;
}

declare module 'js-base64/old/base64-1.7' {
  declare module.exports: any;
}

declare module 'js-base64/package' {
  declare module.exports: any;
}

declare module 'js-base64/test/dankogai' {
  declare module.exports: any;
}

declare module 'js-base64/test/es5' {
  declare module.exports: any;
}

declare module 'js-base64/test/large' {
  declare module.exports: any;
}

declare module 'js-base64/test/yoshinoya' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-base64/base64.js' {
  declare module.exports: $Exports<'js-base64/base64'>;
}
declare module 'js-base64/base64.min.js' {
  declare module.exports: $Exports<'js-base64/base64.min'>;
}
declare module 'js-base64/old/base64-1.7.js' {
  declare module.exports: $Exports<'js-base64/old/base64-1.7'>;
}
declare module 'js-base64/package.js' {
  declare module.exports: $Exports<'js-base64/package'>;
}
declare module 'js-base64/test/dankogai.js' {
  declare module.exports: $Exports<'js-base64/test/dankogai'>;
}
declare module 'js-base64/test/es5.js' {
  declare module.exports: $Exports<'js-base64/test/es5'>;
}
declare module 'js-base64/test/large.js' {
  declare module.exports: $Exports<'js-base64/test/large'>;
}
declare module 'js-base64/test/yoshinoya.js' {
  declare module.exports: $Exports<'js-base64/test/yoshinoya'>;
}
