// flow-typed signature: 0631c74467ab4654495274bc6e1ddb11
// flow-typed version: <<STUB>>/react-prism_v^4.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-prism'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-prism' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-prism/lib/index' {
  declare module.exports: any;
}

declare module 'react-prism/lib/index.test' {
  declare module.exports: any;
}

declare module 'react-prism/lib/PrismCode' {
  declare module.exports: any;
}

declare module 'react-prism/lib/PrismCode.test' {
  declare module.exports: any;
}

declare module 'react-prism/src/lib/index' {
  declare module.exports: any;
}

declare module 'react-prism/src/lib/index.test' {
  declare module.exports: any;
}

declare module 'react-prism/src/lib/PrismCode' {
  declare module.exports: any;
}

declare module 'react-prism/src/lib/PrismCode.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-prism/lib/index.js' {
  declare module.exports: $Exports<'react-prism/lib/index'>;
}
declare module 'react-prism/lib/index.test.js' {
  declare module.exports: $Exports<'react-prism/lib/index.test'>;
}
declare module 'react-prism/lib/PrismCode.js' {
  declare module.exports: $Exports<'react-prism/lib/PrismCode'>;
}
declare module 'react-prism/lib/PrismCode.test.js' {
  declare module.exports: $Exports<'react-prism/lib/PrismCode.test'>;
}
declare module 'react-prism/src/lib/index.js' {
  declare module.exports: $Exports<'react-prism/src/lib/index'>;
}
declare module 'react-prism/src/lib/index.test.js' {
  declare module.exports: $Exports<'react-prism/src/lib/index.test'>;
}
declare module 'react-prism/src/lib/PrismCode.js' {
  declare module.exports: $Exports<'react-prism/src/lib/PrismCode'>;
}
declare module 'react-prism/src/lib/PrismCode.test.js' {
  declare module.exports: $Exports<'react-prism/src/lib/PrismCode.test'>;
}
