// flow-typed signature: 4a6b59dae610040b77a1ff6b4da5d856
// flow-typed version: <<STUB>>/react-collapse_v^2.3.3/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-collapse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-collapse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-collapse/build/react-collapse' {
  declare module.exports: any;
}

declare module 'react-collapse/build/react-collapse.min' {
  declare module.exports: any;
}

declare module 'react-collapse/lib/Collapse' {
  declare module.exports: any;
}

declare module 'react-collapse/lib/index' {
  declare module.exports: any;
}

declare module 'react-collapse/src/Collapse' {
  declare module.exports: any;
}

declare module 'react-collapse/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-collapse/build/react-collapse.js' {
  declare module.exports: $Exports<'react-collapse/build/react-collapse'>;
}
declare module 'react-collapse/build/react-collapse.min.js' {
  declare module.exports: $Exports<'react-collapse/build/react-collapse.min'>;
}
declare module 'react-collapse/lib/Collapse.js' {
  declare module.exports: $Exports<'react-collapse/lib/Collapse'>;
}
declare module 'react-collapse/lib/index.js' {
  declare module.exports: $Exports<'react-collapse/lib/index'>;
}
declare module 'react-collapse/src/Collapse.js' {
  declare module.exports: $Exports<'react-collapse/src/Collapse'>;
}
declare module 'react-collapse/src/index.js' {
  declare module.exports: $Exports<'react-collapse/src/index'>;
}
