// flow-typed signature: b6f2dd3b66e24cf838fb85600d9671bf
// flow-typed version: <<STUB>>/react-svg-morph_v^0.1.10/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-svg-morph'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-svg-morph' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-svg-morph/lib/index' {
  declare module.exports: any;
}

declare module 'react-svg-morph/lib/MorphReplace' {
  declare module.exports: any;
}

declare module 'react-svg-morph/lib/MorphReplaceNative' {
  declare module.exports: any;
}

declare module 'react-svg-morph/lib/MorphReplaceResize' {
  declare module.exports: any;
}

declare module 'react-svg-morph/lib/MorphTransition' {
  declare module.exports: any;
}

declare module 'react-svg-morph/lib/MorphTransitionNative' {
  declare module.exports: any;
}

declare module 'react-svg-morph/lib/MorphTransitionResize' {
  declare module.exports: any;
}

declare module 'react-svg-morph/lib/native' {
  declare module.exports: any;
}

declare module 'react-svg-morph/lib/utils/easing' {
  declare module.exports: any;
}

declare module 'react-svg-morph/lib/utils/helpers' {
  declare module.exports: any;
}

declare module 'react-svg-morph/lib/utils/morph' {
  declare module.exports: any;
}

declare module 'react-svg-morph/lib/utils/normalizeSvg' {
  declare module.exports: any;
}

declare module 'react-svg-morph/lib/utils/pathConverter' {
  declare module.exports: any;
}

declare module 'react-svg-morph/lib/utils/raf' {
  declare module.exports: any;
}

declare module 'react-svg-morph/lib/utils/scalePath' {
  declare module.exports: any;
}

declare module 'react-svg-morph/lib/utils/svglite' {
  declare module.exports: any;
}

declare module 'react-svg-morph/src/index' {
  declare module.exports: any;
}

declare module 'react-svg-morph/src/MorphReplace' {
  declare module.exports: any;
}

declare module 'react-svg-morph/src/MorphReplaceNative' {
  declare module.exports: any;
}

declare module 'react-svg-morph/src/MorphReplaceResize' {
  declare module.exports: any;
}

declare module 'react-svg-morph/src/MorphTransition' {
  declare module.exports: any;
}

declare module 'react-svg-morph/src/MorphTransitionNative' {
  declare module.exports: any;
}

declare module 'react-svg-morph/src/MorphTransitionResize' {
  declare module.exports: any;
}

declare module 'react-svg-morph/src/native' {
  declare module.exports: any;
}

declare module 'react-svg-morph/src/utils/easing' {
  declare module.exports: any;
}

declare module 'react-svg-morph/src/utils/helpers' {
  declare module.exports: any;
}

declare module 'react-svg-morph/src/utils/morph' {
  declare module.exports: any;
}

declare module 'react-svg-morph/src/utils/normalizeSvg' {
  declare module.exports: any;
}

declare module 'react-svg-morph/src/utils/pathConverter' {
  declare module.exports: any;
}

declare module 'react-svg-morph/src/utils/raf' {
  declare module.exports: any;
}

declare module 'react-svg-morph/src/utils/scalePath' {
  declare module.exports: any;
}

declare module 'react-svg-morph/src/utils/svglite' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-svg-morph/lib/index.js' {
  declare module.exports: $Exports<'react-svg-morph/lib/index'>;
}
declare module 'react-svg-morph/lib/MorphReplace.js' {
  declare module.exports: $Exports<'react-svg-morph/lib/MorphReplace'>;
}
declare module 'react-svg-morph/lib/MorphReplaceNative.js' {
  declare module.exports: $Exports<'react-svg-morph/lib/MorphReplaceNative'>;
}
declare module 'react-svg-morph/lib/MorphReplaceResize.js' {
  declare module.exports: $Exports<'react-svg-morph/lib/MorphReplaceResize'>;
}
declare module 'react-svg-morph/lib/MorphTransition.js' {
  declare module.exports: $Exports<'react-svg-morph/lib/MorphTransition'>;
}
declare module 'react-svg-morph/lib/MorphTransitionNative.js' {
  declare module.exports: $Exports<'react-svg-morph/lib/MorphTransitionNative'>;
}
declare module 'react-svg-morph/lib/MorphTransitionResize.js' {
  declare module.exports: $Exports<'react-svg-morph/lib/MorphTransitionResize'>;
}
declare module 'react-svg-morph/lib/native.js' {
  declare module.exports: $Exports<'react-svg-morph/lib/native'>;
}
declare module 'react-svg-morph/lib/utils/easing.js' {
  declare module.exports: $Exports<'react-svg-morph/lib/utils/easing'>;
}
declare module 'react-svg-morph/lib/utils/helpers.js' {
  declare module.exports: $Exports<'react-svg-morph/lib/utils/helpers'>;
}
declare module 'react-svg-morph/lib/utils/morph.js' {
  declare module.exports: $Exports<'react-svg-morph/lib/utils/morph'>;
}
declare module 'react-svg-morph/lib/utils/normalizeSvg.js' {
  declare module.exports: $Exports<'react-svg-morph/lib/utils/normalizeSvg'>;
}
declare module 'react-svg-morph/lib/utils/pathConverter.js' {
  declare module.exports: $Exports<'react-svg-morph/lib/utils/pathConverter'>;
}
declare module 'react-svg-morph/lib/utils/raf.js' {
  declare module.exports: $Exports<'react-svg-morph/lib/utils/raf'>;
}
declare module 'react-svg-morph/lib/utils/scalePath.js' {
  declare module.exports: $Exports<'react-svg-morph/lib/utils/scalePath'>;
}
declare module 'react-svg-morph/lib/utils/svglite.js' {
  declare module.exports: $Exports<'react-svg-morph/lib/utils/svglite'>;
}
declare module 'react-svg-morph/src/index.js' {
  declare module.exports: $Exports<'react-svg-morph/src/index'>;
}
declare module 'react-svg-morph/src/MorphReplace.js' {
  declare module.exports: $Exports<'react-svg-morph/src/MorphReplace'>;
}
declare module 'react-svg-morph/src/MorphReplaceNative.js' {
  declare module.exports: $Exports<'react-svg-morph/src/MorphReplaceNative'>;
}
declare module 'react-svg-morph/src/MorphReplaceResize.js' {
  declare module.exports: $Exports<'react-svg-morph/src/MorphReplaceResize'>;
}
declare module 'react-svg-morph/src/MorphTransition.js' {
  declare module.exports: $Exports<'react-svg-morph/src/MorphTransition'>;
}
declare module 'react-svg-morph/src/MorphTransitionNative.js' {
  declare module.exports: $Exports<'react-svg-morph/src/MorphTransitionNative'>;
}
declare module 'react-svg-morph/src/MorphTransitionResize.js' {
  declare module.exports: $Exports<'react-svg-morph/src/MorphTransitionResize'>;
}
declare module 'react-svg-morph/src/native.js' {
  declare module.exports: $Exports<'react-svg-morph/src/native'>;
}
declare module 'react-svg-morph/src/utils/easing.js' {
  declare module.exports: $Exports<'react-svg-morph/src/utils/easing'>;
}
declare module 'react-svg-morph/src/utils/helpers.js' {
  declare module.exports: $Exports<'react-svg-morph/src/utils/helpers'>;
}
declare module 'react-svg-morph/src/utils/morph.js' {
  declare module.exports: $Exports<'react-svg-morph/src/utils/morph'>;
}
declare module 'react-svg-morph/src/utils/normalizeSvg.js' {
  declare module.exports: $Exports<'react-svg-morph/src/utils/normalizeSvg'>;
}
declare module 'react-svg-morph/src/utils/pathConverter.js' {
  declare module.exports: $Exports<'react-svg-morph/src/utils/pathConverter'>;
}
declare module 'react-svg-morph/src/utils/raf.js' {
  declare module.exports: $Exports<'react-svg-morph/src/utils/raf'>;
}
declare module 'react-svg-morph/src/utils/scalePath.js' {
  declare module.exports: $Exports<'react-svg-morph/src/utils/scalePath'>;
}
declare module 'react-svg-morph/src/utils/svglite.js' {
  declare module.exports: $Exports<'react-svg-morph/src/utils/svglite'>;
}
