// flow-typed signature: 2d0cdffa12c4beaf0e7814724b8d2757
// flow-typed version: <<STUB>>/react-highlight_v^0.9.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-highlight'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-highlight' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-highlight/gulpfile' {
  declare module.exports: any;
}

declare module 'react-highlight/karma.conf' {
  declare module.exports: any;
}

declare module 'react-highlight/lib/index' {
  declare module.exports: any;
}

declare module 'react-highlight/lib/optimized' {
  declare module.exports: any;
}

declare module 'react-highlight/src/index' {
  declare module.exports: any;
}

declare module 'react-highlight/src/optimized' {
  declare module.exports: any;
}

declare module 'react-highlight/test/highlight.test' {
  declare module.exports: any;
}

declare module 'react-highlight/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-highlight/gulpfile.js' {
  declare module.exports: $Exports<'react-highlight/gulpfile'>;
}
declare module 'react-highlight/index' {
  declare module.exports: $Exports<'react-highlight'>;
}
declare module 'react-highlight/index.js' {
  declare module.exports: $Exports<'react-highlight'>;
}
declare module 'react-highlight/karma.conf.js' {
  declare module.exports: $Exports<'react-highlight/karma.conf'>;
}
declare module 'react-highlight/lib/index.js' {
  declare module.exports: $Exports<'react-highlight/lib/index'>;
}
declare module 'react-highlight/lib/optimized.js' {
  declare module.exports: $Exports<'react-highlight/lib/optimized'>;
}
declare module 'react-highlight/src/index.js' {
  declare module.exports: $Exports<'react-highlight/src/index'>;
}
declare module 'react-highlight/src/optimized.js' {
  declare module.exports: $Exports<'react-highlight/src/optimized'>;
}
declare module 'react-highlight/test/highlight.test.js' {
  declare module.exports: $Exports<'react-highlight/test/highlight.test'>;
}
declare module 'react-highlight/webpack.config.js' {
  declare module.exports: $Exports<'react-highlight/webpack.config'>;
}
