// flow-typed signature: bf4c8bc66f1aa7ba129f649b86317310
// flow-typed version: <<STUB>>/remove-flow-types-loader_v^1.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remove-flow-types-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remove-flow-types-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remove-flow-types-loader/test/expected' {
  declare module.exports: any;
}

declare module 'remove-flow-types-loader/test/source' {
  declare module.exports: any;
}

declare module 'remove-flow-types-loader/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remove-flow-types-loader/index' {
  declare module.exports: $Exports<'remove-flow-types-loader'>;
}
declare module 'remove-flow-types-loader/index.js' {
  declare module.exports: $Exports<'remove-flow-types-loader'>;
}
declare module 'remove-flow-types-loader/test/expected.js' {
  declare module.exports: $Exports<'remove-flow-types-loader/test/expected'>;
}
declare module 'remove-flow-types-loader/test/source.js' {
  declare module.exports: $Exports<'remove-flow-types-loader/test/source'>;
}
declare module 'remove-flow-types-loader/webpack.config.js' {
  declare module.exports: $Exports<'remove-flow-types-loader/webpack.config'>;
}
