// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/62e37b17e1ec502ad642903d745d1b1ac8ff74d6/js-base64/index.d.ts
declare module 'js-base64' {
    namespace JSBase64 {
        const Base64: Base64Static
        interface Base64Static {
            /**
             * .encode
             * @param {String} string
             * @return {String}
             */
            encode(base64: string): string;

            /**
             * .encodeURI
             * @param {String} string
             * @return {String}
             */
            encodeURI(base64: string): string

            /**
             * .decode
             * @param {String} string
             * @return {String}
             */
            decode(base64: string): string

            /**
             * Library version
             */
            VERSION:string
        }
    }
    export = JSBase64
}
