// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/984933df7c89afcb97e42adbe37b6df5dd7b253c/react-router/index.d.ts
declare module 'react-router' {
  import * as React from 'react';
  import * as H from 'history';


  interface MemoryRouterProps {
    initialEntries?: H.Location[];
    initialIndex?: number;
    getUserConfirmation?: () => void;
    keyLength?: number;
  }
  class MemoryRouter extends React.Component<MemoryRouterProps, void> {}


  interface PromptProps {
    message: string | ((location: H.Location) => void);
    when?: boolean;
  }
  class Prompt extends React.Component<PromptProps, void> {}


  interface RedirectProps {
    to: H.LocationDescriptor;
    push?: boolean;
    from?: string;
  }
  class Redirect extends React.Component<RedirectProps, void> {}


  interface RouteComponentProps<P> {
    match: match<P>;
    location: H.Location;
    history: H.History;
  }

  interface RouteProps {
    location?: H.Location;
    component?: React.SFC<RouteComponentProps<any> | void> | React.ComponentClass<RouteComponentProps<any> | void>;
    render?: (props: RouteComponentProps<any>) => React.ReactNode;
    children?: (props: RouteComponentProps<any>) => React.ReactNode | React.ReactNode;
    path?: string;
    exact?: boolean;
    strict?: boolean;
  }
  class Route extends React.Component<RouteProps, void> {}


  interface RouterProps {
    history: any;
  }
  class Router extends React.Component<RouterProps, void> {}


  interface StaticRouterProps extends RouterProps {
    basename?: string;
    location?: string | object;
    context?: object;
  }
  class StaticRouter extends React.Component<StaticRouterProps, void> {}


  interface SwitchProps extends RouteProps {
  }
  class Switch extends React.Component<SwitchProps, void> {}


  interface match<P> {
    params: P;
    isExact: boolean;
    path: string;
    url: string;
  }


  function matchPath<P>(pathname: string, props: RouteProps): match<P> | null;


  function withRouter(component: React.SFC<RouteComponentProps<any>> | React.ComponentClass<RouteComponentProps<any>>): React.ComponentClass<any>;


  export {
    MemoryRouter,
    Prompt,
    Redirect,
    RouteComponentProps, // TypeScript specific, not from React Router itself
    RouteProps, // TypeScript specific, not from React Router itself
    Route,
    Router,
    StaticRouter,
    Switch,
    match, // TypeScript specific, not from React Router itself
    matchPath,
    withRouter
  }
}
